0 0 dataAuditErrors
281 0 NWVIA_StampErrorFloat
282 0 NWVIA_StampErrorMult
283 0 NWVIA_StampErrorConnect
288 0 NWELLterm_StampErrorFloat
289 0 NWELLterm_StampErrorMult
290 0 NWELLterm_StampErrorConnect
295 0 JVARterm_StampErrorFloat
296 0 JVARterm_StampErrorMult
297 0 JVARterm_StampErrorConnect
302 0 JVARanode_StampErrorFloat
303 0 JVARanode_StampErrorMult
304 0 JVARanode_StampErrorConnect
309 0 PWVIA_StampErrorFloat
310 0 PWVIA_StampErrorMult
311 0 PWVIA_StampErrorConnect
316 0 Pwell_StampErrorFloat
317 0 Pwell_StampErrorMult
318 0 Pwell_StampErrorConnect
323 0 PWNBVIA_StampErrorFloat
324 0 PWNBVIA_StampErrorMult
325 0 PWNBVIA_StampErrorConnect
330 0 ISOPWELL_StampErrorFloat
331 0 ISOPWELL_StampErrorMult
332 0 ISOPWELL_StampErrorConnect
337 0 SUBVIA_StampErrorFloat
338 0 SUBVIA_StampErrorMult
339 0 SUBVIA_StampErrorConnect
344 0 PSUB_StampErrorFloat
345 0 PSUB_StampErrorMult
346 0 PSUB_StampErrorConnect
351 0 NBVIA_StampErrorFloat
352 0 NBVIA_StampErrorMult
353 0 NBVIA_StampErrorConnect
358 0 Nburied_StampErrorFloat
359 0 Nburied_StampErrorMult
360 0 Nburied_StampErrorConnect
1283 0 malformed device POLYRES
1284 0 malformed device POLYHRES
1285 0 malformed device NSDRES
1286 0 malformed device ISONSDRES
1287 0 malformed device PSDRES
1288 0 malformed device NWELLRES
1289 0 malformed device M1res
1290 0 malformed device M2res
1291 0 malformed device M3res
1292 0 malformed device M4res
1293 0 malformed device M5res
1294 0 malformed device M6res
1295 0 malformed device MIMCAP
1296 0 malformed device PMOSCAP
1297 0 malformed device NMOSCAP
1298 0 malformed device ISONMOSCAP
1299 0 malformed device INDUCTOR
1300 0 malformed device VPNP
1301 0 malformed device PNP
1302 0 malformed device NPN
1303 0 malformed device NMOS
1304 0 malformed device ISONMOS
1305 0 malformed device NMOSHV
1306 0 malformed device ISONMOSHV
1307 0 malformed device NMOSRF
1308 0 malformed device ISONMOSRF
1309 0 malformed device PMOS
1310 0 malformed device PMOSHV
1311 0 malformed device PMOSRF
1312 0 malformed device NDIODE
1313 0 malformed device PDIODE
1314 0 malformed device JVARNF
1315 0 malformed device JVARW40
1512 0 unstable device for JVARW40_DIODE_33
1513 0 unpreserved device JVARW40_DIODE_33
1514 0 unstable device for JVARNF_DIODE_32
1515 0 unpreserved device JVARNF_DIODE_32
1516 0 unstable device for PDIODE_DIODE_31
1517 0 unpreserved device PDIODE_DIODE_31
1518 0 unstable device for NDIODE_DIODE_30
1519 0 unpreserved device NDIODE_DIODE_30
1520 0 unstable device for PMOSRF_MOS_29
1521 0 unpreserved device PMOSRF_MOS_29
1522 0 unstable device for PMOSHV_MOS_28
1523 0 unpreserved device PMOSHV_MOS_28
1524 0 unstable device for PMOS_MOS_27
1525 0 unpreserved device PMOS_MOS_27
1526 0 unstable device for ISONMOSRF_MOS_26
1527 0 unpreserved device ISONMOSRF_MOS_26
1528 0 unstable device for NMOSRF_MOS_25
1529 0 unpreserved device NMOSRF_MOS_25
1530 0 unstable device for ISONMOSHV_MOS_24
1531 0 unpreserved device ISONMOSHV_MOS_24
1532 0 unstable device for NMOSHV_MOS_23
1533 0 unpreserved device NMOSHV_MOS_23
1534 0 unstable device for ISONMOS_MOS_22
1535 0 unpreserved device ISONMOS_MOS_22
1536 0 unstable device for NMOS_MOS_21
1537 0 unpreserved device NMOS_MOS_21
1538 0 unstable device for NPN_BJT_20
1539 0 unpreserved device NPN_BJT_20
1540 0 unstable device for PNP_BJT_19
1541 0 unpreserved device PNP_BJT_19
1542 0 unstable device for VPNP_BJT_18
1543 0 unpreserved device VPNP_BJT_18
1544 0 unstable device for INDUCTOR_Device_17
1545 0 unpreserved device INDUCTOR_Device_17
1546 0 unstable device for ISONMOSCAP_MOS_16
1547 0 unpreserved device ISONMOSCAP_MOS_16
1548 0 unstable device for NMOSCAP_MOS_15
1549 0 unpreserved device NMOSCAP_MOS_15
1550 0 unstable device for PMOSCAP_MOS_14
1551 0 unpreserved device PMOSCAP_MOS_14
1552 0 unstable device for MIMCAP_CAP_13
1553 0 unpreserved device MIMCAP_CAP_13
1554 0 unstable device for M6res_RES_12
1555 0 unpreserved device M6res_RES_12
1556 0 unstable device for M5res_RES_11
1557 0 unpreserved device M5res_RES_11
1558 0 unstable device for M4res_RES_10
1559 0 unpreserved device M4res_RES_10
1560 0 unstable device for M3res_RES_9
1561 0 unpreserved device M3res_RES_9
1562 0 unstable device for M2res_RES_8
1563 0 unpreserved device M2res_RES_8
1564 0 unstable device for M1res_RES_7
1565 0 unpreserved device M1res_RES_7
1566 0 unstable device for NWELLRES_RES_6
1567 0 unpreserved device NWELLRES_RES_6
1568 0 unstable device for PSDRES_RES_5
1569 0 unpreserved device PSDRES_RES_5
1570 0 unstable device for ISONSDRES_RES_4
1571 0 unpreserved device ISONSDRES_RES_4
1572 0 unstable device for NSDRES_RES_3
1573 0 unpreserved device NSDRES_RES_3
1574 0 unstable device for POLYHRES_RES_2
1575 0 unpreserved device POLYHRES_RES_2
1576 0 unstable device for POLYRES_RES_1
1577 0 unpreserved device POLYRES_RES_1
