0 0 dataAuditErrors
1 0 non45Errors
2 0 offGridErrors
74 0 offGridShapeErrors: off grid polygon on layer BJTdum
76 0 offGridShapeErrors: off grid polygon on layer Bondpad
78 0 offGridShapeErrors: off grid polygon on layer CapMetal
80 0 offGridShapeErrors: off grid polygon on layer Cont
82 0 offGridShapeErrors: off grid polygon on layer IND2dummy
84 0 offGridShapeErrors: off grid polygon on layer IND3dummy
86 0 offGridShapeErrors: off grid polygon on layer INDdummy
88 0 offGridShapeErrors: off grid polygon on layer JVAR1dummy
90 0 offGridShapeErrors: off grid polygon on layer JVAR2dummy
92 0 offGridShapeErrors: off grid polygon on layer JVAR3dummy
94 0 offGridShapeErrors: off grid polygon on layer M1dummy
96 0 offGridShapeErrors: off grid polygon on layer M2dummy
98 0 offGridShapeErrors: off grid polygon on layer M3dummy
100 0 offGridShapeErrors: off grid polygon on layer M4dummy
102 0 offGridShapeErrors: off grid polygon on layer M5dummy
104 0 offGridShapeErrors: off grid polygon on layer M6dummy
106 0 offGridShapeErrors: off grid polygon on layer Metal1
108 0 offGridShapeErrors: off grid polygon on layer Metal2
110 0 offGridShapeErrors: off grid polygon on layer Metal3
112 0 offGridShapeErrors: off grid polygon on layer Metal4
114 0 offGridShapeErrors: off grid polygon on layer Metal5
116 0 offGridShapeErrors: off grid polygon on layer Metal6
118 0 offGridShapeErrors: off grid polygon on layer NPNdummy
120 0 offGridShapeErrors: off grid polygon on layer Nburied
122 0 offGridShapeErrors: off grid polygon on layer Nimp
124 0 offGridShapeErrors: off grid polygon on layer Nwell
126 0 offGridShapeErrors: off grid polygon on layer Oxide
128 0 offGridShapeErrors: off grid polygon on layer PNPdummy
130 0 offGridShapeErrors: off grid polygon on layer Pimp
132 0 offGridShapeErrors: off grid polygon on layer Poly
134 0 offGridShapeErrors: off grid polygon on layer Pwell
136 0 offGridShapeErrors: off grid polygon on layer ResWdum
138 0 offGridShapeErrors: off grid polygon on layer Resdum
140 0 offGridShapeErrors: off grid polygon on layer ThickOxide
142 0 offGridShapeErrors: off grid polygon on layer Via1
144 0 offGridShapeErrors: off grid polygon on layer Via2
146 0 offGridShapeErrors: off grid polygon on layer Via3
148 0 offGridShapeErrors: off grid polygon on layer Via4
150 0 offGridShapeErrors: off grid polygon on layer Via5
152 0 non45 degree polygon on layer BJTdum
154 0 non45 degree polygon on layer Bondpad
156 0 non45 degree polygon on layer CapMetal
158 0 non45 degree polygon on layer Cont
160 0 non45 degree polygon on layer IND2dummy
162 0 non45 degree polygon on layer IND3dummy
164 0 non45 degree polygon on layer INDdummy
166 0 non45 degree polygon on layer JVAR1dummy
168 0 non45 degree polygon on layer JVAR2dummy
170 0 non45 degree polygon on layer JVAR3dummy
172 0 non45 degree polygon on layer M1dummy
174 0 non45 degree polygon on layer M2dummy
176 0 non45 degree polygon on layer M3dummy
178 0 non45 degree polygon on layer M4dummy
180 0 non45 degree polygon on layer M5dummy
182 0 non45 degree polygon on layer M6dummy
183 0 non45 degree polygon on layer Metal1
184 0 non45 degree polygon on layer Metal2
185 0 non45 degree polygon on layer Metal3
186 0 non45 degree polygon on layer Metal4
187 0 non45 degree polygon on layer Metal5
188 0 non45 degree polygon on layer Metal6
190 0 non45 degree polygon on layer NPNdummy
192 0 non45 degree polygon on layer Nburied
194 0 non45 degree polygon on layer Nimp
196 0 non45 degree polygon on layer Nwell
198 0 non45 degree polygon on layer Oxide
200 0 non45 degree polygon on layer PNPdummy
202 0 non45 degree polygon on layer Pimp
204 0 non45 degree polygon on layer Poly
206 0 non45 degree polygon on layer Pwell
208 0 non45 degree polygon on layer ResWdum
210 0 non45 degree polygon on layer Resdum
212 0 non45 degree polygon on layer ThickOxide
214 0 non45 degree polygon on layer Via1
216 0 non45 degree polygon on layer Via2
218 0 non45 degree polygon on layer Via3
220 0 non45 degree polygon on layer Via4
222 0 non45 degree polygon on layer Via5
223 0 acute angle on layer BJTdum
224 0 acute angle on layer IND2dummy
225 0 acute angle on layer IND3dummy
226 0 acute angle on layer INDdummy
227 0 acute angle on layer JVAR1dummy
228 0 acute angle on layer JVAR2dummy
229 0 acute angle on layer JVAR3dummy
230 0 acute angle on layer M1dummy
231 0 acute angle on layer M2dummy
232 0 acute angle on layer M3dummy
233 0 acute angle on layer M4dummy
234 0 acute angle on layer M5dummy
235 0 acute angle on layer M6dummy
236 0 acute angle on layer NPNdummy
237 0 acute angle on layer PNPdummy
238 0 acute angle on layer ResWdum
239 0 acute angle on layer Resdum
294 0 NWVIA_StampErrorFloat
295 0 NWVIA_StampErrorMult
301 0 NWELLterm_StampErrorFloat
302 0 NWELLterm_StampErrorMult
308 0 JVARterm_StampErrorFloat
309 0 JVARterm_StampErrorMult
315 0 JVARanode_StampErrorFloat
316 0 JVARanode_StampErrorMult
322 0 PWVIA_StampErrorFloat
323 0 PWVIA_StampErrorMult
329 0 Pwell_StampErrorFloat
330 0 Pwell_StampErrorMult
336 0 PWNBVIA_StampErrorFloat
337 0 PWNBVIA_StampErrorMult
343 0 ISOPWELL_StampErrorFloat
344 0 ISOPWELL_StampErrorMult
350 0 SUBVIA_StampErrorFloat
351 0 SUBVIA_StampErrorMult
357 0 PSUB_StampErrorFloat
358 0 PSUB_StampErrorMult
364 0 NBVIA_StampErrorFloat
365 0 NBVIA_StampErrorMult
371 0 Nburied_StampErrorFloat
372 0 Nburied_StampErrorMult
377 0 0A: Nburied width must be >= 1.0 um
379 0 0B: Nburied to Nburied spacing must be >= 1.0 um
380 0 1A: Nwell width must be >= 1.0 um
382 0 1B: Nwell to Nwell spacing must be >= 1.0 um
384 0 1C: Nburied to Nwell enclosure must be >= 0.3 um
385 0 1D: Pwell width must be >= 1.0 um
387 0 1E: Pwell to Pwell spacing must be >= 1.0 um
389 0 1F: Nburied to Pwell enclosure must be >= 0.3 um
391 0 1F: Nburied to Pwell enclosure must be >= 0.3 um
392 0 2A: Oxide width must be >= 0.4 um
394 0 2B: Oxide to Oxide spacing must be >= 0.3 um
396 0 2C: Nwell to Oxide enclosure must be >= 0.5 um
398 0 2C: Nwell to Oxide enclosure must be >= 0.5 um
400 0 2C: Pwell to Oxide enclosure must be >= 0.5 um
402 0 2C: Pwell to Oxide enclosure must be >= 0.5 um
404 0 2D: Nwell to Oxide spacing must be >= 0.5 um
405 0 2D: Nwell to Oxide spacing must be >= 0.5 um
407 0 2D: Pwell to Oxide spacing must be >= 0.5 um
408 0 2D: Pwell to Oxide spacing must be >= 0.5 um
409 0 2.5A: ThickOxide width must be >= 0.5 um
411 0 2.5B: ThickOxide to ThickOxide spacing must be >= 0.4 um
412 0 2.5D: ThickOxide to Oxide spacing must be >= 0.25 um
419 0 2.5E: ThickOxide to Poly spacing must be >= 0.4 um
420 0 2.5E: ThickOxide to Poly spacing must be >= 0.4 um
423 0 2.5F: ThickOxide to Poly enclosure must be >= 0.4 um
425 0 2.5F: ThickOxide to Poly enclosure must be >= 0.4 um
427 0 2.5C: ThickOxide to Oxide enclosure must be >= 0.25 um
428 0 3A: Nimp width must be >= 0.4 um
430 0 3B: Nimp to Nimp spacing must be >= 0.4 um
432 0 3C: Nimp to Oxide enclosure must be >= 0.2 um
434 0 3D: Nburied to Nimp enclosure must be >= 0.6 um
435 0 4A: Pimp width must be >= 0.4 um
437 0 4B: Pimp to Pimp spacing must be >= 0.4 um
439 0 4C: Pimp to Oxide enclosure must be >= 0.2 um
441 0 4D: Nburied to Pimp enclosure must be >= 0.6 um
442 0 5A: Poly width must be >= 0.18 um
444 0 5B: Poly to Poly spacing must be >= 0.3 um
446 0 5C: Poly to Oxide enclosure must be >= 0.2 um
448 0 5D: Oxide to Poly enclosure must be >= 0.4 um
449 0 5E: Oxide to Poly spacing must be >= 0.2 um
451 0 6B: Cont to Cont spacing must be >= 0.2 um
453 0 6A: Cont shapes must be 0.2x0.2 rectangles
455 0 6C: Oxide to Cont enclosure must be >= 0.2 um
457 0 6C: Oxide to Cont enclosure must be >= 0.2 um
460 0 6E: Poly to Cont spacing must be >= 0.2 um
461 0 6E: Poly to Cont spacing must be >= 0.2 um
463 0 6G: Nimp to Cont enclosure must be >= 0.1 um
465 0 6G: Nimp to Cont enclosure must be >= 0.1 um
470 0 6H: Oxide to Cont spacing must be >= 0.2 um
471 0 6H: Oxide to Cont spacing must be >= 0.2 um
473 0 6D: Poly to Cont enclosure must be >= 0.2 um
475 0 6D: Poly to Cont enclosure must be >= 0.2 um
477 0 6F: Pimp to Cont enclosure must be >= 0.1 um
479 0 6F: Pimp to Cont enclosure must be >= 0.1 um
480 0 7A: Metal1 width must be >= 0.3 um
482 0 7B: Metal1 to Metal1 spacing must be >= 0.3 um
484 0 7C: Metal1 to Cont enclosure must be >= 0.1 um
486 0 7C: Metal1 to Cont enclosure must be >= 0.1 um
487 0 9A: Metal2 width must be >= 0.3 um
489 0 9B: Metal2 to Metal2 spacing must be >= 0.3 um
491 0 9C: Metal2 to Via1 enclosure must be >= 0.1 um
493 0 9C: Metal2 to Via1 enclosure must be >= 0.1 um
494 0 11A: Metal3 width must be >= 0.3 um
496 0 11B: Metal3 to Metal3 spacing must be >= 0.3 um
498 0 11C: Metal3 to Via2NoCapInd enclosure must be >= 0.1 um
500 0 11C: Metal3 to Via2NoCapInd enclosure must be >= 0.1 um
501 0 15A: Metal4 width must be >= 0.3 um
503 0 15B: Metal4 to Metal4 spacing must be >= 0.3 um
505 0 15C: Metal4 to Via3 enclosure must be >= 0.1 um
507 0 15C: Metal4 to Via3 enclosure must be >= 0.1 um
508 0 17A: Metal5 width must be >= 0.3 um
510 0 17B: Metal5 to Metal5 spacing must be >= 0.3 um
512 0 17C: Metal5 to Via4 enclosure must be >= 0.1 um
514 0 17C: Metal5 to Via4 enclosure must be >= 0.1 um
515 0 19A: Metal6 width must be >= 0.3 um
517 0 19B: Metal6 to Metal6 spacing must be >= 0.3 um
519 0 19C: Metal6 to Via5 enclosure must be >= 0.1 um
521 0 19C: Metal6 to Via5 enclosure must be >= 0.1 um
523 0 8B: Via1 to Via1 spacing must be >= 0.3 um
525 0 8A: Via1 shapes must be 0.2x0.2 rectangles
527 0 8C: Metal1 to Via1 enclosure must be >= 0.1 um
529 0 8C: Metal1 to Via1 enclosure must be >= 0.1 um
531 0 10B: Via2 to Via2 spacing must be >= 0.3 um
533 0 10A: Via2 shapes must be 0.2x0.2 rectangles
535 0 10C: Metal2 to Via2 enclosure must be >= 0.1 um
537 0 10C: Metal2 to Via2 enclosure must be >= 0.1 um
539 0 14B: Via3 to Via3 spacing must be >= 0.3 um
541 0 14A: Via3 shapes must be 0.2x0.2 rectangles
543 0 14C: Metal3 to Via3 enclosure must be >= 0.1 um
545 0 14C: Metal3 to Via3 enclosure must be >= 0.1 um
547 0 16B: Via4 to Via4 spacing must be >= 0.3 um
549 0 16A: Via4 shapes must be 0.2x0.2 rectangles
551 0 16C: Metal4 to Via4 enclosure must be >= 0.1 um
553 0 16C: Metal4 to Via4 enclosure must be >= 0.1 um
555 0 18B: Via5 to Via5 spacing must be >= 0.3 um
557 0 18A: Via5 shapes must be 0.2x0.2 rectangles
559 0 18C: Metal5 to Via5 enclosure must be >= 0.1 um
561 0 18C: Metal5 to Via5 enclosure must be >= 0.1 um
563 0 12D: CapMetal to Metal3 enclosure must be >= 0.3 um
564 0 12A: CapMetal width must be >= 0.5 um
566 0 12B: Metal2 to Via2Cap enclosure must be >= 0.1 um
568 0 12B: Metal2 to Via2Cap enclosure must be >= 0.1 um
570 0 12C: CapMetal to Via2Cap enclosure must be >= 0.2 um
572 0 12C: CapMetal to Via2Cap enclosure must be >= 0.2 um
574 0 11D: Metal3 to Via2Cap enclosure must be >= 0.1 um
576 0 11D: Metal3 to Via2Cap enclosure must be >= 0.1 um
578 0 20C: Metal1 to Bondpad enclosure must be == 3.0 um
580 0 20C: Metal1 to Bondpad enclosure must be == 3.0 um
582 0 20D: Metal2 to Bondpad enclosure must be == 3.0 um
584 0 20D: Metal2 to Bondpad enclosure must be == 3.0 um
586 0 20E: Metal3 to Bondpad enclosure must be == 3.0 um
588 0 20E: Metal3 to Bondpad enclosure must be == 3.0 um
590 0 20F: Metal4 to Bondpad enclosure must be == 3.0 um
592 0 20F: Metal4 to Bondpad enclosure must be == 3.0 um
594 0 20G: Metal5 to Bondpad enclosure must be == 3.0 um
596 0 20G: Metal5 to Bondpad enclosure must be == 3.0 um
598 0 20H: Metal6 to Bondpad enclosure must be == 3.0 um
600 0 20H: Metal6 to Bondpad enclosure must be == 3.0 um
601 0 20A: Minimum Pad width = 45.0
603 0 20B: Minimum Pad spacing to Pad = 10.0
704 0 13A1: P+SD to NW tap spacing must be <= 10.0 um
807 0 13A2: N+SD to Iso Psub tap spacing must be <= 10.0 um
912 0 13A3: N+SD to Psub tap spacing must be <= 10.0 um
1015 0 13A3: N+SD to PW tap spacing must be <= 10.0 um
